Loading Service
evolving

Something went wrong...


ERROR MESSAGE:
'Unable to retrieve job result. Job cfklsg92k6plbnj8cob0 has failed:\n2023-02-13T02:19:26.583085103Z Setting up watches.\n2023-02-13T02:19:26.583085103Z Watches established.\n2023-02-13T02:19:28.031481511Z INFO:     Started server process [7]\n2023-02-13T02:19:28.031532939Z INFO:     Waiting for application startup.\n2023-02-13T02:19:28.031689690Z INFO:     Application startup complete.\n2023-02-13T02:19:28.032418465Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n2023-02-13T02:20:14.197015289Z INFO:     127.0.0.1:34808 - "POST /run HTTP/1.1" 202 Accepted\n2023-02-13T02:24:25.562071578Z programruntime.runtime_backend - ERROR Job compilation status is error for job estimator_cfklsg92k6plbnj8cob0_9e76_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R4, 0, 1, 10. Error code: 9999.\n2023-02-13T02:24:25.564589801Z --- Logging error ---\n2023-02-13T02:24:25.566535756Z Traceback (most recent call last):\n2023-02-13T02:24:25.566576222Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T02:24:25.566576222Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T02:24:25.566576222Z   File "/code/./program.py", line 1439, in main\n2023-02-13T02:24:25.566576222Z     result = job.result()\n2023-02-13T02:24:25.566602070Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T02:24:25.566602070Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T02:24:25.566602070Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T02:24:25.566602070Z     return self._future.result()\n2023-02-13T02:24:25.566602070Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T02:24:25.566602070Z     return self.__get_result()\n2023-02-13T02:24:25.566602070Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:24:25.566602070Z     raise self._exception\n2023-02-13T02:24:25.566602070Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T02:24:25.566602070Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T02:24:25.566602070Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T02:24:25.566602070Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T02:24:25.566602070Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T02:24:25.566602070Z     result = [x.result() for x in jobs]\n2023-02-13T02:24:25.566602070Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T02:24:25.566602070Z     result = [x.result() for x in jobs]\n2023-02-13T02:24:25.566602070Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T02:24:25.566602070Z     raw_result = self._future.result(timeout)\n2023-02-13T02:24:25.566626005Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T02:24:25.566626005Z     return self.__get_result()\n2023-02-13T02:24:25.566626005Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:24:25.566626005Z     raise self._exception\n2023-02-13T02:24:25.566626005Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T02:24:25.566626005Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T02:24:25.566626005Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T02:24:25.566626005Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T02:24:25.566626005Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T02:24:25.566626005Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T02:24:25.566626005Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T02:24:25.566626005Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T02:24:25.566626005Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T02:24:25.566626005Z     raise ErrorType(error_msg)\n2023-02-13T02:24:25.566668986Z RuntimeError: Job compilation status is error for job estimator_cfklsg92k6plbnj8cob0_9e76_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R4, 0, 1, 10. Error code: 9999.\n2023-02-13T02:24:25.566668986Z \n2023-02-13T02:24:25.566668986Z During handling of the above exception, another exception occurred:\n2023-02-13T02:24:25.566668986Z \n2023-02-13T02:24:25.566668986Z Traceback (most recent call last):\n2023-02-13T02:24:25.566668986Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit\n2023-02-13T02:24:25.566668986Z     msg = self.format(record)\n2023-02-13T02:24:25.566668986Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format\n2023-02-13T02:24:25.566668986Z     return fmt.format(record)\n2023-02-13T02:24:25.566668986Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format\n2023-02-13T02:24:25.566668986Z     record.message = record.getMessage()\n2023-02-13T02:24:25.566668986Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage\n2023-02-13T02:24:25.566668986Z     msg = msg % self.args\n2023-02-13T02:24:25.566668986Z TypeError: not all arguments converted during string formatting\n2023-02-13T02:24:25.566668986Z Call stack:\n2023-02-13T02:24:25.567300456Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap\n2023-02-13T02:24:25.567300456Z     self._bootstrap_inner()\n2023-02-13T02:24:25.567300456Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner\n2023-02-13T02:24:25.567300456Z     self.run()\n2023-02-13T02:24:25.567300456Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run\n2023-02-13T02:24:25.567300456Z     result = context.run(func, *args)\n2023-02-13T02:24:25.567300456Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T02:24:25.567300456Z     starter.execute()\n2023-02-13T02:24:25.567300456Z   File "/provider/programruntime/program_starter_wrapper.py", line 95, in execute\n2023-02-13T02:24:25.567300456Z     logger.error(\n2023-02-13T02:24:25.567330620Z Message: \'Error executing program job cfklsg92k6plbnj8cob0\'\n2023-02-13T02:24:25.567330620Z Arguments: (RuntimeError(\'Job compilation status is error for job estimator_cfklsg92k6plbnj8cob0_9e76_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R4, 0, 1, 10. Error code: 9999.\'),)\n2023-02-13T02:24:25.607000889Z webserver-starter - ERROR Failed to execute program: Job compilation status is error for job estimator_cfklsg92k6plbnj8cob0_9e76_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R4, 0, 1, 10. Error code: 9999.\n2023-02-13T02:24:25.607000889Z Traceback (most recent call last):\n2023-02-13T02:24:25.607000889Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T02:24:25.607000889Z     starter.execute()\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute\n2023-02-13T02:24:25.607000889Z     raise ex\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T02:24:25.607000889Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T02:24:25.607000889Z   File "/code/./program.py", line 1439, in main\n2023-02-13T02:24:25.607000889Z     result = job.result()\n2023-02-13T02:24:25.607000889Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T02:24:25.607000889Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T02:24:25.607000889Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T02:24:25.607000889Z     return self._future.result()\n2023-02-13T02:24:25.607000889Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T02:24:25.607000889Z     return self.__get_result()\n2023-02-13T02:24:25.607000889Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:24:25.607000889Z     raise self._exception\n2023-02-13T02:24:25.607000889Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T02:24:25.607000889Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T02:24:25.607000889Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T02:24:25.607000889Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T02:24:25.607000889Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T02:24:25.607000889Z     result = [x.result() for x in jobs]\n2023-02-13T02:24:25.607000889Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T02:24:25.607000889Z     result = [x.result() for x in jobs]\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T02:24:25.607000889Z     raw_result = self._future.result(timeout)\n2023-02-13T02:24:25.607000889Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T02:24:25.607000889Z     return self.__get_result()\n2023-02-13T02:24:25.607000889Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:24:25.607000889Z     raise self._exception\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T02:24:25.607000889Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T02:24:25.607000889Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T02:24:25.607000889Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T02:24:25.607000889Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T02:24:25.607000889Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T02:24:25.607000889Z     raise ErrorType(error_msg)\n2023-02-13T02:24:25.607000889Z RuntimeError: Job compilation status is error for job estimator_cfklsg92k6plbnj8cob0_9e76_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R4, 0, 1, 10. Error code: 9999.\n2023-02-13T02:24:25.611239410Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-02-13T02:24:25.611553287Z Termination marker file found. Kill process (7).\n'


Job ID: cfklsg92k6plbnj8cob0. Job status: JobStatus.ERROR.
Starting trial number 2...

Creating new session...


Something went wrong...


ERROR MESSAGE:
'Unable to retrieve job result. Job cfkpup92k6plbnja26n0 has failed:\n2023-02-13T02:28:29.012579544Z Setting up watches.\n2023-02-13T02:28:29.012579544Z Watches established.\n2023-02-13T02:28:30.237889366Z INFO:     Started server process [7]\n2023-02-13T02:28:30.237889366Z INFO:     Waiting for application startup.\n2023-02-13T02:28:30.237979858Z INFO:     Application startup complete.\n2023-02-13T02:28:30.238900459Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n2023-02-13T02:29:25.386377335Z INFO:     127.0.0.1:33278 - "POST /run HTTP/1.1" 202 Accepted\n2023-02-13T02:33:37.885485928Z programruntime.runtime_backend - ERROR Job compilation status is error for job estimator_cfkpup92k6plbnja26n0_91b2_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R10, 0, 1, 10. Error code: 9999.\n2023-02-13T02:33:37.890062159Z --- Logging error ---\n2023-02-13T02:33:37.892280767Z Traceback (most recent call last):\n2023-02-13T02:33:37.892307873Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T02:33:37.892307873Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T02:33:37.892307873Z   File "/code/./program.py", line 1439, in main\n2023-02-13T02:33:37.892307873Z     result = job.result()\n2023-02-13T02:33:37.892307873Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T02:33:37.892307873Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T02:33:37.892307873Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T02:33:37.892307873Z     return self._future.result()\n2023-02-13T02:33:37.892307873Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T02:33:37.892307873Z     return self.__get_result()\n2023-02-13T02:33:37.892307873Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:33:37.892307873Z     raise self._exception\n2023-02-13T02:33:37.892307873Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T02:33:37.892307873Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T02:33:37.892325216Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T02:33:37.892325216Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T02:33:37.892325216Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T02:33:37.892325216Z     result = [x.result() for x in jobs]\n2023-02-13T02:33:37.892325216Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T02:33:37.892325216Z     result = [x.result() for x in jobs]\n2023-02-13T02:33:37.892325216Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T02:33:37.892325216Z     raw_result = self._future.result(timeout)\n2023-02-13T02:33:37.892325216Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T02:33:37.892325216Z     return self.__get_result()\n2023-02-13T02:33:37.892325216Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:33:37.892325216Z     raise self._exception\n2023-02-13T02:33:37.892325216Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T02:33:37.892325216Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T02:33:37.892364125Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T02:33:37.892364125Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T02:33:37.892364125Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T02:33:37.892364125Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T02:33:37.892364125Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T02:33:37.892364125Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T02:33:37.892364125Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T02:33:37.892364125Z     raise ErrorType(error_msg)\n2023-02-13T02:33:37.892364125Z RuntimeError: Job compilation status is error for job estimator_cfkpup92k6plbnja26n0_91b2_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R10, 0, 1, 10. Error code: 9999.\n2023-02-13T02:33:37.892364125Z \n2023-02-13T02:33:37.892364125Z During handling of the above exception, another exception occurred:\n2023-02-13T02:33:37.892364125Z \n2023-02-13T02:33:37.892364125Z Traceback (most recent call last):\n2023-02-13T02:33:37.892377908Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit\n2023-02-13T02:33:37.892377908Z     msg = self.format(record)\n2023-02-13T02:33:37.892377908Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format\n2023-02-13T02:33:37.892377908Z     return fmt.format(record)\n2023-02-13T02:33:37.892377908Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format\n2023-02-13T02:33:37.892377908Z     record.message = record.getMessage()\n2023-02-13T02:33:37.892377908Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage\n2023-02-13T02:33:37.892377908Z     msg = msg % self.args\n2023-02-13T02:33:37.892387361Z TypeError: not all arguments converted during string formatting\n2023-02-13T02:33:37.892397212Z Call stack:\n2023-02-13T02:33:37.893197721Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap\n2023-02-13T02:33:37.893197721Z     self._bootstrap_inner()\n2023-02-13T02:33:37.893197721Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner\n2023-02-13T02:33:37.893197721Z     self.run()\n2023-02-13T02:33:37.893211341Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run\n2023-02-13T02:33:37.893211341Z     result = context.run(func, *args)\n2023-02-13T02:33:37.893211341Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T02:33:37.893211341Z     starter.execute()\n2023-02-13T02:33:37.893211341Z   File "/provider/programruntime/program_starter_wrapper.py", line 95, in execute\n2023-02-13T02:33:37.893211341Z     logger.error(\n2023-02-13T02:33:37.893222882Z Message: \'Error executing program job cfkpup92k6plbnja26n0\'\n2023-02-13T02:33:37.893222882Z Arguments: (RuntimeError(\'Job compilation status is error for job estimator_cfkpup92k6plbnja26n0_91b2_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R10, 0, 1, 10. Error code: 9999.\'),)\n2023-02-13T02:33:37.932884365Z webserver-starter - ERROR Failed to execute program: Job compilation status is error for job estimator_cfkpup92k6plbnja26n0_91b2_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R10, 0, 1, 10. Error code: 9999.\n2023-02-13T02:33:37.932884365Z Traceback (most recent call last):\n2023-02-13T02:33:37.932884365Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T02:33:37.932884365Z     starter.execute()\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute\n2023-02-13T02:33:37.932884365Z     raise ex\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T02:33:37.932884365Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T02:33:37.932884365Z   File "/code/./program.py", line 1439, in main\n2023-02-13T02:33:37.932884365Z     result = job.result()\n2023-02-13T02:33:37.932884365Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T02:33:37.932884365Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T02:33:37.932884365Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T02:33:37.932884365Z     return self._future.result()\n2023-02-13T02:33:37.932884365Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T02:33:37.932884365Z     return self.__get_result()\n2023-02-13T02:33:37.932884365Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:33:37.932884365Z     raise self._exception\n2023-02-13T02:33:37.932884365Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T02:33:37.932884365Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T02:33:37.932884365Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T02:33:37.932884365Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T02:33:37.932884365Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T02:33:37.932884365Z     result = [x.result() for x in jobs]\n2023-02-13T02:33:37.932884365Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T02:33:37.932884365Z     result = [x.result() for x in jobs]\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T02:33:37.932884365Z     raw_result = self._future.result(timeout)\n2023-02-13T02:33:37.932884365Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T02:33:37.932884365Z     return self.__get_result()\n2023-02-13T02:33:37.932884365Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T02:33:37.932884365Z     raise self._exception\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T02:33:37.932884365Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T02:33:37.932884365Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T02:33:37.932884365Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T02:33:37.932884365Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T02:33:37.932884365Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T02:33:37.932884365Z     raise ErrorType(error_msg)\n2023-02-13T02:33:37.932884365Z RuntimeError: Job compilation status is error for job estimator_cfkpup92k6plbnja26n0_91b2_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R10, 0, 1, 10. Error code: 9999.\n2023-02-13T02:33:37.937110633Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-02-13T02:33:37.937431705Z Termination marker file found. Kill process (7).\n'


Job ID: cfkpup92k6plbnja26n0. Job status: JobStatus.ERROR.
Starting trial number 3...

Creating new session...


Something went wrong...


ERROR MESSAGE:
'Unable to retrieve job result. Job cfkq32ifhdpjaq94ut1g has failed:\n2023-02-13T07:27:02.786432084Z Setting up watches.\n2023-02-13T07:27:02.786432084Z Watches established.\n2023-02-13T07:27:04.075198248Z INFO:     Started server process [7]\n2023-02-13T07:27:04.075253554Z INFO:     Waiting for application startup.\n2023-02-13T07:27:04.075380909Z INFO:     Application startup complete.\n2023-02-13T07:27:04.076420674Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n2023-02-13T07:29:30.462348022Z INFO:     127.0.0.1:52416 - "POST /run HTTP/1.1" 202 Accepted\n2023-02-13T07:33:35.088508880Z programruntime.runtime_backend - ERROR Job compilation status is error for job estimator_cfkq32ifhdpjaq94ut1g_8121_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R15, 0, 1, 10. Error code: 9999.\n2023-02-13T07:33:35.090003431Z --- Logging error ---\n2023-02-13T07:33:35.091617080Z Traceback (most recent call last):\n2023-02-13T07:33:35.091617080Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T07:33:35.091617080Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T07:33:35.091617080Z   File "/code/./program.py", line 1439, in main\n2023-02-13T07:33:35.091617080Z     result = job.result()\n2023-02-13T07:33:35.091617080Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T07:33:35.091617080Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T07:33:35.091643335Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T07:33:35.091643335Z     return self._future.result()\n2023-02-13T07:33:35.091643335Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T07:33:35.091643335Z     return self.__get_result()\n2023-02-13T07:33:35.091643335Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T07:33:35.091643335Z     raise self._exception\n2023-02-13T07:33:35.091643335Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T07:33:35.091643335Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T07:33:35.091643335Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T07:33:35.091643335Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T07:33:35.091643335Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T07:33:35.091643335Z     result = [x.result() for x in jobs]\n2023-02-13T07:33:35.091643335Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T07:33:35.091643335Z     result = [x.result() for x in jobs]\n2023-02-13T07:33:35.091643335Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T07:33:35.091643335Z     raw_result = self._future.result(timeout)\n2023-02-13T07:33:35.091643335Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T07:33:35.091643335Z     return self.__get_result()\n2023-02-13T07:33:35.091643335Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T07:33:35.091643335Z     raise self._exception\n2023-02-13T07:33:35.091643335Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T07:33:35.091643335Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T07:33:35.091679901Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T07:33:35.091679901Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T07:33:35.091679901Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T07:33:35.091679901Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T07:33:35.091679901Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T07:33:35.091679901Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T07:33:35.091679901Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T07:33:35.091679901Z     raise ErrorType(error_msg)\n2023-02-13T07:33:35.091679901Z RuntimeError: Job compilation status is error for job estimator_cfkq32ifhdpjaq94ut1g_8121_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R15, 0, 1, 10. Error code: 9999.\n2023-02-13T07:33:35.091679901Z \n2023-02-13T07:33:35.091679901Z During handling of the above exception, another exception occurred:\n2023-02-13T07:33:35.091679901Z \n2023-02-13T07:33:35.091679901Z Traceback (most recent call last):\n2023-02-13T07:33:35.091692968Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit\n2023-02-13T07:33:35.091692968Z     msg = self.format(record)\n2023-02-13T07:33:35.091692968Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format\n2023-02-13T07:33:35.091692968Z     return fmt.format(record)\n2023-02-13T07:33:35.091692968Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format\n2023-02-13T07:33:35.091692968Z     record.message = record.getMessage()\n2023-02-13T07:33:35.091692968Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage\n2023-02-13T07:33:35.091692968Z     msg = msg % self.args\n2023-02-13T07:33:35.091703126Z TypeError: not all arguments converted during string formatting\n2023-02-13T07:33:35.091703126Z Call stack:\n2023-02-13T07:33:35.092296476Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap\n2023-02-13T07:33:35.092296476Z     self._bootstrap_inner()\n2023-02-13T07:33:35.092296476Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner\n2023-02-13T07:33:35.092296476Z     self.run()\n2023-02-13T07:33:35.092307034Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run\n2023-02-13T07:33:35.092307034Z     result = context.run(func, *args)\n2023-02-13T07:33:35.092307034Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T07:33:35.092307034Z     starter.execute()\n2023-02-13T07:33:35.092307034Z   File "/provider/programruntime/program_starter_wrapper.py", line 95, in execute\n2023-02-13T07:33:35.092307034Z     logger.error(\n2023-02-13T07:33:35.092328952Z Message: \'Error executing program job cfkq32ifhdpjaq94ut1g\'\n2023-02-13T07:33:35.092328952Z Arguments: (RuntimeError(\'Job compilation status is error for job estimator_cfkq32ifhdpjaq94ut1g_8121_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R15, 0, 1, 10. Error code: 9999.\'),)\n2023-02-13T07:33:35.115143413Z webserver-starter - ERROR Failed to execute program: Job compilation status is error for job estimator_cfkq32ifhdpjaq94ut1g_8121_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R15, 0, 1, 10. Error code: 9999.\n2023-02-13T07:33:35.115143413Z Traceback (most recent call last):\n2023-02-13T07:33:35.115143413Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-13T07:33:35.115143413Z     starter.execute()\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute\n2023-02-13T07:33:35.115143413Z     raise ex\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-13T07:33:35.115143413Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-13T07:33:35.115143413Z   File "/code/./program.py", line 1439, in main\n2023-02-13T07:33:35.115143413Z     result = job.result()\n2023-02-13T07:33:35.115143413Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-13T07:33:35.115143413Z     result: EstimatorResult = self.base_job.result()\n2023-02-13T07:33:35.115143413Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-13T07:33:35.115143413Z     return self._future.result()\n2023-02-13T07:33:35.115143413Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-13T07:33:35.115143413Z     return self.__get_result()\n2023-02-13T07:33:35.115143413Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T07:33:35.115143413Z     raise self._exception\n2023-02-13T07:33:35.115143413Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-13T07:33:35.115143413Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-13T07:33:35.115143413Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-13T07:33:35.115143413Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-13T07:33:35.115143413Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-13T07:33:35.115143413Z     result = [x.result() for x in jobs]\n2023-02-13T07:33:35.115143413Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-13T07:33:35.115143413Z     result = [x.result() for x in jobs]\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-13T07:33:35.115143413Z     raw_result = self._future.result(timeout)\n2023-02-13T07:33:35.115143413Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-13T07:33:35.115143413Z     return self.__get_result()\n2023-02-13T07:33:35.115143413Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-13T07:33:35.115143413Z     raise self._exception\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/runtime_backend.py", line 491, in _start_job_submit\n2023-02-13T07:33:35.115143413Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/runtime_backend.py", line 542, in _job_submit\n2023-02-13T07:33:35.115143413Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/runtime_backend.py", line 587, in _job_submit_to_backend\n2023-02-13T07:33:35.115143413Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/runtime_backend.py", line 718, in verify_job_build\n2023-02-13T07:33:35.115143413Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-13T07:33:35.115143413Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-13T07:33:35.115143413Z     raise ErrorType(error_msg)\n2023-02-13T07:33:35.115143413Z RuntimeError: Job compilation status is error for job estimator_cfkq32ifhdpjaq94ut1g_8121_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R15, 0, 1, 10. Error code: 9999.\n2023-02-13T07:33:35.119258700Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-02-13T07:33:35.119569017Z Termination marker file found. Kill process (7).\n'

