Evolving
Traceback (most recent call last):
  File "script_hw.py", line 84, in <module>
    )
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/var_qte.py", line 155, in evolve
    evolved_state, param_values, time_points = self._evolve(
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/var_qte.py", line 228, in _evolve
    final_param_values, param_values, time_points = ode_solver.run(time)
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/solvers/ode/var_qte_ode_solver.py", line 76, in run
    sol = solve(
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/scipy/integrate/_ivp/ivp.py", line 591, in solve_ivp
    message = solver.step()
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/scipy/integrate/_ivp/base.py", line 181, in step
    success, message = self._step_impl()
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/solvers/ode/forward_euler_solver.py", line 66, in _step_impl
    self.y = list(np.add(self.y, self._step_length * self.fun(self.t, self.y)))
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/scipy/integrate/_ivp/base.py", line 138, in fun
    return self.fun_single(t, y)
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/scipy/integrate/_ivp/base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/solvers/ode/ode_function.py", line 36, in var_qte_ode_function
    ode_grad_res, _, _ = self._varqte_linear_solver.solve_lse(
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/solvers/var_qte_linear_solver.py", line 114, in solve_lse
    metric_tensor_lse_lhs = self._var_principle.metric_tensor(self._ansatz, param_values)
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/gibbs/qfiwrapper.py", line 10, in wrapped_fun
    result = function(*args, **kwargs)
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/time_evolvers/variational/variational_principles/variational_principle.py", line 71, in metric_tensor
    metric_tensor = self.qgt.run([ansatz], [param_values], [None]).result().qgts[0]
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/algorithms/gradients/base_qgt.py", line 164, in run
    job.submit()
  File "/home/ubuntu/gibbsenv/lib/python3.8/site-packages/qiskit/primitives/primitive_job.py", line 44, in submit
    future = executor.submit(self._function, *self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Evolving
'Unable to retrieve job result. Job cfn2gqsp10prblrs73t0 has failed:\n2023-02-16T14:07:56.333127912Z Setting up watches.\n2023-02-16T14:07:56.333127912Z Watches established.\n2023-02-16T14:07:57.515596409Z INFO:     Started server process [7]\n2023-02-16T14:07:57.515596409Z INFO:     Waiting for application startup.\n2023-02-16T14:07:57.515717122Z INFO:     Application startup complete.\n2023-02-16T14:07:57.516403964Z INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)\n2023-02-16T14:10:21.738709678Z INFO:     127.0.0.1:54410 - "POST /run HTTP/1.1" 202 Accepted\n2023-02-16T14:25:52.785951142Z programruntime.runtime_backend - ERROR Job compilation status is error for job estimator_cfn2gqsp10prblrs73t0_a98b_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R9, 0, 1, 33. Error code: 9999.\n2023-02-16T14:25:52.787104123Z --- Logging error ---\n2023-02-16T14:25:52.788789440Z Traceback (most recent call last):\n2023-02-16T14:25:52.788789440Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-16T14:25:52.788789440Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-16T14:25:52.788789440Z   File "/code/./program.py", line 1439, in main\n2023-02-16T14:25:52.788789440Z     result = job.result()\n2023-02-16T14:25:52.788818437Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-16T14:25:52.788818437Z     result: EstimatorResult = self.base_job.result()\n2023-02-16T14:25:52.788818437Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-16T14:25:52.788818437Z     return self._future.result()\n2023-02-16T14:25:52.788818437Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-16T14:25:52.788818437Z     return self.__get_result()\n2023-02-16T14:25:52.788818437Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-16T14:25:52.788818437Z     raise self._exception\n2023-02-16T14:25:52.788818437Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-16T14:25:52.788818437Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-16T14:25:52.788818437Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-16T14:25:52.788818437Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-16T14:25:52.788818437Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-16T14:25:52.788818437Z     result = [x.result() for x in jobs]\n2023-02-16T14:25:52.788818437Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-16T14:25:52.788818437Z     result = [x.result() for x in jobs]\n2023-02-16T14:25:52.788818437Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-16T14:25:52.788818437Z     raw_result = self._future.result(timeout)\n2023-02-16T14:25:52.788818437Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-16T14:25:52.788818437Z     return self.__get_result()\n2023-02-16T14:25:52.788818437Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-16T14:25:52.788818437Z     raise self._exception\n2023-02-16T14:25:52.788835617Z   File "/provider/programruntime/runtime_backend.py", line 490, in _start_job_submit\n2023-02-16T14:25:52.788835617Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-16T14:25:52.788835617Z   File "/provider/programruntime/runtime_backend.py", line 541, in _job_submit\n2023-02-16T14:25:52.788835617Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-16T14:25:52.788835617Z   File "/provider/programruntime/runtime_backend.py", line 586, in _job_submit_to_backend\n2023-02-16T14:25:52.788835617Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-16T14:25:52.788835617Z   File "/provider/programruntime/runtime_backend.py", line 717, in verify_job_build\n2023-02-16T14:25:52.788835617Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-16T14:25:52.788835617Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-16T14:25:52.788835617Z     raise ErrorType(error_msg)\n2023-02-16T14:25:52.788862899Z RuntimeError: Job compilation status is error for job estimator_cfn2gqsp10prblrs73t0_a98b_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R9, 0, 1, 33. Error code: 9999.\n2023-02-16T14:25:52.788862899Z \n2023-02-16T14:25:52.788862899Z During handling of the above exception, another exception occurred:\n2023-02-16T14:25:52.788862899Z \n2023-02-16T14:25:52.788862899Z Traceback (most recent call last):\n2023-02-16T14:25:52.788862899Z   File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit\n2023-02-16T14:25:52.788862899Z     msg = self.format(record)\n2023-02-16T14:25:52.788862899Z   File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format\n2023-02-16T14:25:52.788862899Z     return fmt.format(record)\n2023-02-16T14:25:52.788862899Z   File "/usr/lib64/python3.9/logging/__init__.py", line 663, in format\n2023-02-16T14:25:52.788862899Z     record.message = record.getMessage()\n2023-02-16T14:25:52.788874482Z   File "/usr/lib64/python3.9/logging/__init__.py", line 367, in getMessage\n2023-02-16T14:25:52.788874482Z     msg = msg % self.args\n2023-02-16T14:25:52.788874482Z TypeError: not all arguments converted during string formatting\n2023-02-16T14:25:52.788885602Z Call stack:\n2023-02-16T14:25:52.789480082Z   File "/usr/lib64/python3.9/threading.py", line 937, in _bootstrap\n2023-02-16T14:25:52.789480082Z     self._bootstrap_inner()\n2023-02-16T14:25:52.789480082Z   File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner\n2023-02-16T14:25:52.789480082Z     self.run()\n2023-02-16T14:25:52.789500747Z   File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run\n2023-02-16T14:25:52.789500747Z     result = context.run(func, *args)\n2023-02-16T14:25:52.789500747Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-16T14:25:52.789500747Z     starter.execute()\n2023-02-16T14:25:52.789500747Z   File "/provider/programruntime/program_starter_wrapper.py", line 95, in execute\n2023-02-16T14:25:52.789500747Z     logger.error(\n2023-02-16T14:25:52.789511236Z Message: \'Error executing program job cfn2gqsp10prblrs73t0\'\n2023-02-16T14:25:52.789511236Z Arguments: (RuntimeError(\'Job compilation status is error for job estimator_cfn2gqsp10prblrs73t0_a98b_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R9, 0, 1, 33. Error code: 9999.\'),)\n2023-02-16T14:25:52.837338391Z webserver-starter - ERROR Failed to execute program: Job compilation status is error for job estimator_cfn2gqsp10prblrs73t0_a98b_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R9, 0, 1, 33. Error code: 9999.\n2023-02-16T14:25:52.837338391Z Traceback (most recent call last):\n2023-02-16T14:25:52.837338391Z   File "/provider/server/main.py", line 75, in execute_program\n2023-02-16T14:25:52.837338391Z     starter.execute()\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/program_starter_wrapper.py", line 99, in execute\n2023-02-16T14:25:52.837338391Z     raise ex\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/program_starter_wrapper.py", line 91, in execute\n2023-02-16T14:25:52.837338391Z     final_result = self.main(backend, self.messenger, **self.user_params)\n2023-02-16T14:25:52.837338391Z   File "/code/./program.py", line 1439, in main\n2023-02-16T14:25:52.837338391Z     result = job.result()\n2023-02-16T14:25:52.837338391Z   File "/opt/app-root/lib64/python3.9/site-packages/zne/meta/job.py", line 60, in result\n2023-02-16T14:25:52.837338391Z     result: EstimatorResult = self.base_job.result()\n2023-02-16T14:25:52.837338391Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result\n2023-02-16T14:25:52.837338391Z     return self._future.result()\n2023-02-16T14:25:52.837338391Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result\n2023-02-16T14:25:52.837338391Z     return self.__get_result()\n2023-02-16T14:25:52.837338391Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-16T14:25:52.837338391Z     raise self._exception\n2023-02-16T14:25:52.837338391Z   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run\n2023-02-16T14:25:52.837338391Z     result = self.fn(*self.args, **self.kwargs)\n2023-02-16T14:25:52.837338391Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 257, in _call\n2023-02-16T14:25:52.837338391Z     result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)\n2023-02-16T14:25:52.837338391Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in _run_circuits\n2023-02-16T14:25:52.837338391Z     result = [x.result() for x in jobs]\n2023-02-16T14:25:52.837338391Z   File "/opt/app-root/lib64/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 67, in <listcomp>\n2023-02-16T14:25:52.837338391Z     result = [x.result() for x in jobs]\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/runtime_job.py", line 73, in result\n2023-02-16T14:25:52.837338391Z     raw_result = self._future.result(timeout)\n2023-02-16T14:25:52.837338391Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result\n2023-02-16T14:25:52.837338391Z     return self.__get_result()\n2023-02-16T14:25:52.837338391Z   File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result\n2023-02-16T14:25:52.837338391Z     raise self._exception\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/runtime_backend.py", line 490, in _start_job_submit\n2023-02-16T14:25:52.837338391Z     raw_result, resp_job_id = await self._job_submit(\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/runtime_backend.py", line 541, in _job_submit\n2023-02-16T14:25:52.837338391Z     raw_result, resp_job_id = await self._job_submit_to_backend(\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/runtime_backend.py", line 586, in _job_submit_to_backend\n2023-02-16T14:25:52.837338391Z     await self.verify_job_build(backend_name, job_id, trace_id)\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/runtime_backend.py", line 717, in verify_job_build\n2023-02-16T14:25:52.837338391Z     log_and_raise(__name__, err_msg, RuntimeError)\n2023-02-16T14:25:52.837338391Z   File "/provider/programruntime/utils.py", line 174, in log_and_raise\n2023-02-16T14:25:52.837338391Z     raise ErrorType(error_msg)\n2023-02-16T14:25:52.837338391Z RuntimeError: Job compilation status is error for job estimator_cfn2gqsp10prblrs73t0_a98b_0: Failure during build: Insufficient buffer time on channel 0 to initiate playback instruction: PW 1, R9, 0, 1, 33. Error code: 9999.\n2023-02-16T14:25:52.842989390Z /pod-data/ CLOSE_WRITE,CLOSE terminated\n2023-02-16T14:25:52.843370814Z Termination marker file found. Kill process (7).\n'
[0.]
